### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [gatheringhallstudios/MHWorldDatabase#109]
So now that this code is MIT licensed #78 , are you ok with the inclusion of this app in F-Droid?

**Comment by jaysondc** [comment]
Sure! Is there anything specific you need from us?

**Comment by Poussinou** [comment]
Sorry for the late response

Please [open a RFP on F-Droid side](https://gitlab.com/fdroid/rfp/issues), so we can check that everything is ok, and proceed with the inclusion of your app 👍

**Comment by Poussinou** [comment]
Here you go with the RFP https://gitlab.com/fdroid/rfp/issues/1221

**Comment by IzzySoft** [comment]
@jaysondc it would be great if you could establish [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo here. That way you cannot only maintain summary/description yourself (without the need of additional MRs to get them updated with F-Droid), but also provide screenshots to show up with the app description. You know, the talking image versus 1k words and all that :wink:

Once you've done so and have a tag covering it, please let us know so we can process the RFP @Poussinou opened. Thanks!

**Comment by jaysondc** [comment]
@IzzySoft I've setup fastlane. Go ahead and add the configuration you need to publish to f-droid.

**Comment by IzzySoft** [comment]
@jaysondc thanks, Fastlane looks good (just the screenshots are rather large – not sure if F-Droid "compresses" them or ships them as-is, which for users with a small data plan might just take a big bite when taking a look). Before it can be used at F-Droid, it needs to be covered by a tag nevertheless. Are there any plans for a new tag?

**Comment by jaysondc** [comment]
Yep. I'll tag when we push our next release to the store.

**Comment by IzzySoft** [comment]
Please ping me then when the tag is there (no use to process it before then, or it would show up without description).

**Comment by jaysondc** [comment]
@IzzySoft, The v2.0.0 tag was just released.

**Comment by IzzySoft** [comment]
Thanks @jaysondc – I've triggered the bot for a rescan (just to make sure it recognizes fastlane), and after its report will add metadata and kick the issue upstairs to our packagers.

**Comment by jaysondc** [comment]
Sorry the APK is even bigger now :/. I imported the new set of assets as PNG instead of vectors because I was lazy.

**Comment by IzzySoft** [comment]
Well, you can replace them by SVGs with the next release and sell that as "massively decreased APK size" :laughing: If you make it in time, that could be the one initially included with F-Droid then.
