### ISSUE TITLE
Discord Server Link Broken?

### ISSUE THREAD

**Issue by DeveloperPaul123** [gatheringhallstudios/MHWorldDatabase#125]
The discord server invite link seems to be broken (at least for me). Can this be confirmed by anyone else?

**Comment by jamie1192** [comment]
The link is fine (just tried it again myself). This happens when you're not logged in to Discord in the browser that you accept the invite in.

**Comment by DeveloperPaul123** [comment]
Good call, that fixed it for me. Thanks!
