### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by Poussinou** [gatheringhallstudios/MHWorldDatabase#78]
Hi,

I would like to know the license of this source code. Once you have choose one, like GNU GPLv3, we could talk about the fact to add your app to [F-Droid](https://f-droid.org/) if it respects the inclusion policy :)

You can find some documentation [here](https://f-droid.org/docs/) about F-Droid.

**Comment by CarlosFdez** [comment]
Sorry, we were still deciding between MIT or GPL. The team chose MIT and the license has been updated..

**Comment by tpoisseau** [comment]
Hi,
the [MIT License](https://en.wikipedia.org/wiki/MIT_License) is compatible with GPL.

I know that publish app in another store can be time consuming, but if you have time and want publish it on F-Droid I think you can do it.

Please take a look here : https://f-droid.org/en/docs/Inclusion_Policy/

If you do, peoples who wan't escape from Google supremacy coul'd install your app from F-Droid instead Play Store.

Best regards

**Comment by Poussinou** [comment]
@tpoisseau let's continue this in #109 :)
